version: '3'

services:
  nginx:
    restart: always
    build:
      context: nginx
    container_name: nginx
    tty: true
    ports:
      - "8080:80"
    networks: 
      - node-network
    depends_on:
      - app
    
  app:
    build: 
      context: nodejs
    container_name: app
    networks: 
      - node-network
    volumes:
      - ./nodejs:/usr/src/app
    tty: true
    depends_on: 
      - db
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge